In [1]:
!pip install transformers datasets evaluate accelerate scikit-learn gradio

Requirement already satisfied: transformers in d:\anaconda\lib\site-packages (5.13.0)
Requirement already satisfied: datasets in d:\anaconda\lib\site-packages (5.0.0)
Requirement already satisfied: evaluate in d:\anaconda\lib\site-packages (0.4.6)
Requirement already satisfied: accelerate in d:\anaconda\lib\site-packages (1.14.0)
Requirement already satisfied: scikit-learn in c:\users\computer valley\appdata\roaming\python\python313\site-packages (1.9.0)
Requirement already satisfied: gradio in d:\anaconda\lib\site-packages (6.20.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in d:\anaconda\lib\site-packages (from transformers) (1.23.0)
Requirement already satisfied: numpy>=1.17 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from transformers) (2.2.5)
Requirement already satisfied: packaging>=20.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in d:\anaconda\lib\site-packages (from transformers) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in d:\anaconda\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in d:\anaconda\lib\site-packages (from transformers) (0.20.0)
Requirement already satisfied: safetensors>=0.8.0 in d:\anaconda\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in d:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in d:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in d:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in d:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in d:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in d:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: colorama in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: anyio in d:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.10.0)
Requirement already satisfied: certifi in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in d:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.10)
Requirement already satisfied: h11>=0.16 in d:\anaconda\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in d:\anaconda\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from datasets) (2.3.1)
Requirement already satisfied: requests>=2.32.2 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from datasets) (2.32.3)
Requirement already satisfied: xxhash in d:\anaconda\lib\site-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in d:\anaconda\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in d:\anaconda\lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: psutil in d:\anaconda\lib\site-packages (from accelerate) (7.0.0)
Requirement already satisfied: torch>=2.0.0 in d:\anaconda\lib\site-packages (from accelerate) (2.13.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.4.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.22.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: audioop-lts<=0.2.2 in d:\anaconda\lib\site-packages (from gradio) (0.2.2)
Requirement already satisfied: brotli>=1.1.0 in d:\anaconda\lib\site-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in d:\anaconda\lib\site-packages (from gradio) (0.139.0)
Requirement already satisfied: gradio-client==2.5.0 in d:\anaconda\lib\site-packages (from gradio) (2.5.0)
Requirement already satisfied: groovy~=0.1 in d:\anaconda\lib\site-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in d:\anaconda\lib\site-packages (from gradio) (0.4.1)
Requirement already satisfied: jinja2<4.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (3.0.3)
Requirement already satisfied: orjson~=3.0 in d:\anaconda\lib\site-packages (from gradio) (3.11.9)
Requirement already satisfied: pillow<13.0,>=8.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (11.2.1)
Requirement already satisfied: pydantic<=3.0,>=2.0 in d:\anaconda\lib\site-packages (from gradio) (2.12.4)
Requirement already satisfied: pydub<1.0 in d:\anaconda\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in d:\anaconda\lib\site-packages (from gradio) (0.0.32)
Requirement already satisfied: pytz>=2017.2 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (2025.2)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in d:\anaconda\lib\site-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in d:\anaconda\lib\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=1.0.1 in d:\anaconda\lib\site-packages (from gradio) (1.3.1)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in d:\anaconda\lib\site-packages (from gradio) (0.13.3)
Requirement already satisfied: uvicorn>=0.14.0 in d:\anaconda\lib\site-packages (from gradio) (0.51.0)
Requirement already satisfied: sniffio>=1.1 in d:\anaconda\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\anaconda\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in d:\anaconda\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in d:\anaconda\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\anaconda\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (2.41.5)
Requirement already satisfied: shellingham>=1.3.0 in d:\anaconda\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in d:\anaconda\lib\site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\anaconda\lib\site-packages (from rich>=10.11.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\anaconda\lib\site-packages (from rich>=10.11.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in d:\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers) (0.1.2)
Requirement already satisfied: setuptools>=77.0.3 in d:\anaconda\lib\site-packages (from torch>=2.0.0->accelerate) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in d:\anaconda\lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from torch>=2.0.0->accelerate) (3.4.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\anaconda\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import torch

from datasets import load_dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

from sklearn.metrics import accuracy_score, f1_score

In [3]:
# checking is cp or gpu is used
print("Torch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

Torch: 2.7.1+cu118
CUDA: True
cuda

In [4]:
dataset = load_dataset("fancyzhx/ag_news")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 120000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 7600
    })
})

In [6]:
dataset["train"][0]

{'text': "Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green again.",
 'label': 2}

In [7]:
dataset["train"].features["label"].names

['World', 'Sports', 'Business', 'Sci/Tech']

In [8]:
# loading tokenizer
tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-uncased"
)

In [9]:
# toinizing the text
def tokenize(batch):

    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=64
    )

In [10]:
tokenized_train = dataset["train"].map(
    tokenize,
    batched=True
)

tokenized_test = dataset["test"].map(
    tokenize,
    batched=True
)

In [11]:
# removing text after tokenizaton
tokenized_train = tokenized_train.remove_columns(["text"])
tokenized_test = tokenized_test.remove_columns(["text"])

tokenized_train = tokenized_train.rename_column(
    "label",
    "labels"
)

tokenized_test = tokenized_test.rename_column(
    "label",
    "labels"
)

In [12]:
# chamging format to pytorch format
tokenized_train.set_format("torch")
tokenized_test.set_format("torch")

In [13]:
# selecting size for training data and teting data
small_train = tokenized_train.shuffle(seed=42).select(range(5000))
small_test = tokenized_test.shuffle(seed=42).select(range(1000))

In [14]:
model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=4
)

model.to(device)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=4, bias=True)
)

In [15]:
print(next(model.parameters()).device)

cuda:0

In [16]:
def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=1)

    accuracy = accuracy_score(labels, predictions)

    f1 = f1_score(
        labels,
        predictions,
        average="weighted"
    )

    return {
        "accuracy": accuracy,
        "f1": f1
    }

In [17]:
training_args = TrainingArguments(

    output_dir="./results",

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=4,

    per_device_eval_batch_size=4,

    num_train_epochs=2,

    weight_decay=0.01,

    fp16=True,

    load_best_model_at_end=True,

    metric_for_best_model="accuracy",

    logging_steps=100,

    report_to="none"
)

In [18]:
trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=small_train,

    eval_dataset=small_test,

    compute_metrics=compute_metrics
)

In [19]:
# training the model
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=2500, training_loss=0.3810238166809082, metrics={'train_runtime': 1120.0663, 'train_samples_per_second': 8.928, 'train_steps_per_second': 2.232, 'total_flos': 328894725120000.0, 'train_loss': 0.3810238166809082, 'epoch': 2.0})

In [20]:
results = trainer.evaluate()

results

{'eval_loss': 0.4371004104614258,
 'eval_accuracy': 0.909,
 'eval_f1': 0.9088201396575569}

In [21]:
print("Accuracy :", results["eval_accuracy"])

print("F1 Score :", results["eval_f1"])

Accuracy : 0.909
F1 Score : 0.9088201396575569

In [22]:
trainer.save_model("saved_model")

tokenizer.save_pretrained("saved_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('saved_model\\tokenizer_config.json', 'saved_model\\tokenizer.json')

In [23]:
import json

labels = dataset["train"].features["label"].names

with open("saved_model/labels.json","w") as f:

    json.dump(labels,f)

In [24]:
text = "Apple unveils its latest AI-powered iPhone with improved performance."

inputs = tokenizer(
    text,
    return_tensors="pt",
    truncation=True,
    padding=True,
    max_length=128
)

inputs = {k: v.to(device) for k, v in inputs.items()}

model.eval()

with torch.no_grad():

    outputs = model(**inputs)

prediction = torch.argmax(outputs.logits, dim=1).item()

print("Prediction:", labels[prediction])

Prediction: Sci/Tech

In [25]:
news = [
    "Microsoft announces a new AI chip.",
    "Pakistan defeats India in the cricket final.",
    "Oil prices rise due to global demand.",
    "The United Nations holds a climate summit."
]

for text in news:

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=64
    )

    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    pred = torch.argmax(outputs.logits, dim=1).item()

    print(f"{text}\nPrediction: {labels[pred]}\n")

Microsoft announces a new AI chip.
Prediction: Sci/Tech

Pakistan defeats India in the cricket final.
Prediction: Sports

Oil prices rise due to global demand.
Prediction: Business

The United Nations holds a climate summit.
Prediction: Sci/Tech

In [27]:
!pip install gradio

Requirement already satisfied: gradio in d:\anaconda\lib\site-packages (6.20.0)
Requirement already satisfied: anyio<5.0,>=3.0 in d:\anaconda\lib\site-packages (from gradio) (4.10.0)
Requirement already satisfied: audioop-lts<=0.2.2 in d:\anaconda\lib\site-packages (from gradio) (0.2.2)
Requirement already satisfied: brotli>=1.1.0 in d:\anaconda\lib\site-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in d:\anaconda\lib\site-packages (from gradio) (0.139.0)
Requirement already satisfied: gradio-client==2.5.0 in d:\anaconda\lib\site-packages (from gradio) (2.5.0)
Requirement already satisfied: groovy~=0.1 in d:\anaconda\lib\site-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in d:\anaconda\lib\site-packages (from gradio) (0.4.1)
Requirement already satisfied: httpx<1.0,>=0.24.1 in d:\anaconda\lib\site-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.2.0 in d:\anaconda\lib\site-packages (from gradio) (1.23.0)
Requirement already satisfied: jinja2<4.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (2.2.5)
Requirement already satisfied: orjson~=3.0 in d:\anaconda\lib\site-packages (from gradio) (3.11.9)
Requirement already satisfied: packaging in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (25.0)
Requirement already satisfied: pandas<4.0,>=1.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (2.3.1)
Requirement already satisfied: pillow<13.0,>=8.0 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (11.2.1)
Requirement already satisfied: pydantic<=3.0,>=2.0 in d:\anaconda\lib\site-packages (from gradio) (2.12.4)
Requirement already satisfied: pydub<1.0 in d:\anaconda\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in d:\anaconda\lib\site-packages (from gradio) (0.0.32)
Requirement already satisfied: pytz>=2017.2 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from gradio) (2025.2)
Requirement already satisfied: pyyaml<7.0,>=5.0 in d:\anaconda\lib\site-packages (from gradio) (6.0.3)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in d:\anaconda\lib\site-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in d:\anaconda\lib\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=1.0.1 in d:\anaconda\lib\site-packages (from gradio) (1.3.1)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in d:\anaconda\lib\site-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in d:\anaconda\lib\site-packages (from gradio) (0.20.0)
Requirement already satisfied: typing-extensions~=4.0 in d:\anaconda\lib\site-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in d:\anaconda\lib\site-packages (from gradio) (0.51.0)
Requirement already satisfied: fsspec in d:\anaconda\lib\site-packages (from gradio-client==2.5.0->gradio) (2025.10.0)
Requirement already satisfied: idna>=2.8 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in d:\anaconda\lib\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.0)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\anaconda\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in d:\anaconda\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from httpx<1.0,>=0.24.1->gradio) (2025.4.26)
Requirement already satisfied: httpcore==1.* in d:\anaconda\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in d:\anaconda\lib\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in d:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.2.0->gradio) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in d:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.2.0->gradio) (3.20.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in d:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.2.0->gradio) (1.5.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from huggingface-hub<2.0,>=1.2.0->gradio) (4.67.1)
Requirement already satisfied: colorama in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.2.0->gradio) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from pandas<4.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in d:\anaconda\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\anaconda\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (2.41.5)
Requirement already satisfied: shellingham>=1.3.0 in d:\anaconda\lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in d:\anaconda\lib\site-packages (from typer<1.0,>=0.12->gradio) (14.2.0)
Requirement already satisfied: six>=1.5 in c:\users\computer valley\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\anaconda\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\anaconda\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in d:\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
import torch
import json
import gradio as gr

from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification

In [29]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tokenizer = AutoTokenizer.from_pretrained("saved_model")

model = AutoModelForSequenceClassification.from_pretrained("saved_model")

model.to(device)

model.eval()

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=4, bias=True)
)

In [30]:
with open("saved_model/labels.json", "r") as f:
    labels = json.load(f)

print(labels)

['World', 'Sports', 'Business', 'Sci/Tech']

In [31]:
def predict_news(news):

    inputs = tokenizer(
        news,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=64
    )

    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    prediction = torch.argmax(outputs.logits, dim=1).item()

    return labels[prediction]

In [32]:
interface = gr.Interface(

    fn=predict_news,

    inputs=gr.Textbox(
        lines=4,
        placeholder="Enter a news headline here..."
    ),

    outputs=gr.Textbox(label="Predicted Category"),

    title="News Topic Classifier Using BERT",

    description="Enter any news headline and BERT will predict its topic."
)

In [33]:
interface.launch()

* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.